import os
os.chdir('\\Users\\Brobi\\Desktop')
s=open('Save.gsf','w')
s.write('#Move this file to the same directory of the game.')
s.write('\n#*Game Save File*')
s.write('\ndev = False')
s.write('\nunlock_all_achievements = False')
s.write('\nrepeat_chapters = False')
s.write('\nnormal_clear = False')
s.write('\nrepeat_amount = 50')
s.write('\nchars_in_line = 55')
s.write('\nrun_off = True')
s.write('\nerror_message = True')
s.write('\nlevel = 0')
s.write('\nxp = 124')
s.write('\nstrength = 30')
s.write('\npush_up_practice = 4')
s.write('\nlift_rocks_practice = 5')
s.write('\nbegin = True')
s.write('\nday_lock1 = False')
s.write('\nday_lock2 = False')
s.write('\nday_lock3 = False')
s.write('\nday_lock4 = False')
s.write('\nday_lock5 = False')
s.write('\nday_lock6 = False')
s.write('\nday_lock7 = False')
s.write('\nday_lock8 = False')
s.write('\nday_lock9 = False')
s.write('\nday_lock10 = False')
s.write('\nday_lock11 = False')
s.write('\nstory_part1 = False')
s.write('\nstory_part2 = False')
s.write('\nstory_part3 = False')
s.write('\nstory_part4 = False')
s.write('\nstory_part5 = False')
s.write('\nstory_part6 = False')
s.write('\nstory_part7 = False')
s.write('\nstory_part8 = False')
s.write('\nstory_part9 = False')
s.write('\nstory_part10 = False')
s.write('\nstory_part11 = False')
s.write('\nstory_part12 = False')
s.write("\ncave_cord1 = ['52, 61, 30', False]")
s.write('\nflashlight = False')
s.write('\nbattery_charger = False')
s.write("\nenemy=['Goblin','Karen','Bat','Skeleton','Zombie','Put Name Here','Crab Rave','No Cell Service','Gertie','Jimmy','Gage']")
s.write("\ncurrent_enemy=''")
s.write('\nmoney = 10.0')
s.write('\nworking_battery_charger = False')
s.write('\nskip = True')
s.write('\none_time = False')
s.write('\nhealth = 0')
s.write('\nstart = True')
s.write('\nattack = False')
s.write('\nvictory_status = False')
s.write('\nseen_notes = 0')
s.write('\ntotal_wins = 0')
s.write('\ncharge_price = 0.9')
s.write('\ncharge_time = 1.2')
s.write('\ncustom_attack = False')
s.write('\nfrying_pan = 0')
s.write('\ndagger = 0')
s.write('\npickaxe = 3')
s.write('\nmachete = 2')
s.write('\nsticks = 2')
s.write('\ncoal = 2')
s.write('\ncomputer_chips = 0')
s.write('\nwires = 0')
s.write('\ngood_batteries = 0')
s.write('\nbad_batteries = 0')
s.write('\nbattery = 5')
s.write('\nthrowing_rocks = 12')
s.write('\nspears = 5')
s.write('\ntorches = 25')
s.write('\nflashlight_use = False')
s.write('\nthrowing_rocks_use = False')
s.write('\npickaxe_use = False')
s.write('\nmachete_use = False')
s.write('\nspears_use = False')
s.write('\ntorch_use = False')
s.write('\nfrying_pan_use = False')
s.write('\ndagger_use = False')
s.write('\nno_light = False')
s.write('\nthrowing_rocks_damage=[7,15]')
s.write('\nspears_damage=[11,17]')
s.write('\npickaxe_damage=[15,19]')
s.write('\nmachete_damage=[17,23]')
s.write('\nred_gem = 0')
s.write('\ngreen_gem = 0')
s.write('\nmagenta_gem = 0')
s.write('\nyellow_gem = 0')
s.write('\nblue_gem = 0')
s.write('\nbuy_count = 13')
s.write('\ncoal_buy = 2.1')
s.write('\ncomputer_chips_buy = 8.4')
s.write('\nwires_buy = 3.9')
s.write('\ngood_batteries_buy = 4.75')
s.write('\nbad_batteries_buy = 3.0')
s.write('\nsticks_buy = 1.25')
s.write('\nthrowing_rocks_buy = 1.25')
s.write('\nspears_buy = 1.75')
s.write('\ntorches_buy = 0.7')
s.write('\npickaxe_buy = 2.1')
s.write('\nfring_pan_buy = 0')
s.write('\ndagger_buy = 0')
s.write('\nsell_count = 13')
s.write('\ncoal_sell = 1.5')
s.write('\ncomputer_chips_sell = 5.0')
s.write('\nwires_sell = 2.4')
s.write('\ngood_batteries_sell = 3.5')
s.write('\nbad_batteries_sell = 2.15')
s.write('\nsticks_sell = 1.0')
s.write('\nthrowing_rocks_sell = 1.25')
s.write('\nspears_sell = 1.0')
s.write('\ntorches_sell = 0.7')
s.write('\npickaxe_sell = 2.1')
s.write('\nmachete_sell = 2.45')
s.write('\nfrying_pan_sell = 0')
s.write('\ndagger_sell = 0')
s.write('\nlet_the_battles_begin = False')
s.write('\nguts_and_glory = False')
s.write('\ni_have_the_power = False')
s.write('\nits_payday = False')
s.write('\nwhicked_chronicle = False')
s.write('\nkeep_it_moving = False')
s.write('\n\n#Developers: Brandon Robinson, Albert Plummer')
s.write('\n#Github Page: github.com/sukadateam')
s.write('\n#Please report any bugs you encounter.')
s.write('\nallow_older_save = False')
s.write("\nversion_save = '0.2.9'")
s.write('\n#Please do not change the version_save variable. It may cause crashes.')
s.write('\n#Instead change allow_older_savefile to True. Uppercase the T and rue is lowercase.')
s.write('\n#Please note. Changing to dev mode and back can cause problems. Please choose one or the other.')
s.close()



