print 'This program is meant to make version look up easy.'
print
print
code=raw_input('What is the code: ')
if code == "0.1.0":
  print 'Current Version 0.1.0:'
  print '1. You can no longer charge batteries if you have non that are currently discharged.'
  print '2. You can no longer change batteries if you don\'t have any that are charged.'
  print '3. skip_story is now skip_intro. This appears in app startup.'
  print '4. Created another chapter to the story. This is chapter 4.'
  print '5. Added a new option so user can see improvements to the application.'
  print '6. Added a new option so user can see their unlocked chapters.'
  print '7. Added a new option so user can change and tweak setting if a problem occurs or for their personal preference.'
  print '8. Fixed a couple of grammatical errors.'
if code == "0.2.0":
  print 'Current Version 0.2.0:'
  print '1. Added a battle program. Users can now fight mobs.'
  print '2. Users can now see how many battles thay have won.'
  print '3. Minor Bug fixes.'
if code == "0.2.1":
  print 'Current Version 0.2.1:'
  print '1. The story now has some more reading space between sections.'
  print '2. The story now can use "settings" instead of just "setting"'
  print '3. You can now open settings from the options menu.'
  print '4. User inputs in intro are now defaulted to a lowercase standpoint.'
  print '5. Adjusted the timing for text to display on screen in the intro.'
  print '6. Grammer corrections in the intro have been improved.'
  print '7. Added a dev startup mode.'
  print '8. Added a item damage page that shows the strength of weapons.'
  print '9. Start will no longer play if you didn\'t choose it.'
  print '10. Added a shop. You can only sell for right now.'
  print '11. You now start with 2 coal and 2 sticks.'
if code == "0.2.2":
  print 'Current Version 0.2.2:'
  print '1. You can now charge batteries in the shop.'
  print '2. Added a def called non_function. Tells the user that something they are trying to do has not been implemented into the game yet.'
  print '3. Fixed several problems with the attack mode.'
  print '4. Spears can now be used in the game as a weapon. You will start with 5 of them.'
  print '5. You will now start with 12 throwing rocks instead of 10.'
if code == "0.2.3":
  print 'Current Version 0.2.3:'
  print '1. Fixed a problem where the story would not progress past the first chapter.'
  print '2. Trading in the shop now works. There are 2 trades available. More will be added in future updates.'
  print '3. Fixed a problem where if you were to not enter anything, then the story would break. Not allowing you to continue.'
  print '4. Added 3 more possible scenes when user uses a spear in battle.'
  print '5. Added place holders for a save and battle_arena function.'
  print '6. Tutorial bag will no longer display if you skip the intro.'
  print '7. User can now only use flashlight and/or torch once per battle.'
  print '8. Quick Settings, Update Info and Version Info no longer appear in app start up. It will only appear when dev=True.'
  print '9. Added a developer tool to change the chapters in game manually. This function is hidden: edit_chapters'
  print '10. Added a few more chapters in the chapters function.'
if code == "0.2.4":
  print 'Current Version 0.2.4:'
  print '1. When exiting the shop, it will no longer ask you to "Hit enter to exit:" twice instead of once.'
  print '2. Enemys now have names in battle.'
  print '3. Removed all_chapters_unlocked feature due to how the code is organized. This feature causes problems.'
  print '4. Fixed a problem where the first chapter would break if a incorrect input was given.'
  print '5. Fixed a ploblem in story where some charcters in chapter 1 would look like it was something out of a movie.'
  print '6. Fixed a problem where battery variable would crash the game because it wasn\'t referenced.'
  print '7. Fixed a problem where if you win a battle sometimes it wouldn\'t recognize that you won.'
  print '8. Added Machete and Pickaxe to the attack function.'
  print '9. Added Machete and Pickaxe to the damage info function.'
  print '10. Added 5 notes in the game. These can be found by exploring the caves.'
  print '11. Added new achievements in the game. You can now also see your unlocked achievements.'
  print '12. Added a cheat to unlock all the achievements in the game.'
  print '13. Changed how the chapters function works in game.'
  print '14. Items now display correctly in the bag.'
  print '15. Adjusted the look of the home menu.'
if code == "0.2.5":
  print 'Current Version 0.2.5:'
  print '1. Added Machete and Pickaxe to sell.'
  print '2. Added Machete and Pickaxe to buy.'
  print '3. Edited the look of the loading page.'
  print '4. Added more enemy names.'
  print '5. Added gems in to the game.'
  print '6. Added a function called gems so user can see what gems they currently have.'
  print '7. Added loot crates for chapters.'
  print '8. You now start with 10.00$ instead of 3.76$'
  print '9. Organized Variables in code.'
  print '10. Collisseum is now implemented into the game. Cannot be accessed without dev mode yet.'
  print '11. You now start with 3 pickaxes instead of 1.'
  print '12. You now start with 2 machetes instead of 1.'
  print '13. Added a load funcion. Cannot be accessed without dev mode yet.'
  print '14. Added a experimental save function. Cannot be accessed without dev mode yet.'
  print '15. Added gems into the shop as a form of trading currency.'
  print '16. Added a new chapter.'
if code == "0.2.6":
  print 'Current Version 0.2.6'
  print '1. Load now tells the user what file extension the game is looking for.'
  print '2. Save now tells the user where the save file is stored.'
  print '3. Load will now automatically troubleshoot some problems that may occur.'
  print '4. Added another developer tool.'
  print '5. Added a developer file. For beta testers.'
  print '6. Added new variabled to save file.'
  print '7. Made it easier for developers to test the game.'
  print '8. Added a 2 new chapters.'
  print '9. Added a 5 new notes.'
  print '10. Fixed a battle problem with chapter 6.'
  print '11. After completing a battle your stats are now displayed on screen not cleared.'
  print '12. Fixed a user input problem of chapter 7.'
  print '13. Fixed a problem where notes() would return a traceback error.'
  print '14. Fixed a problem when trying to recieve a loot crate.'
  print '15. When in developer mode, home page now shows developer choices. These can only be only used in dev mode.'
  print '16. Added the extra chapters in dev edit_chapters for users in dev mode.'
  print '17. Users can now enter dev mode in the game from the home menu.'
if code == "0.2.7":
  print 'Current Version 0.2.7'
  print '1. Added some important info in the save function.'
  print '2. Save function can now only be used in dev mode.'
  print '3. Fixed many grammer errors in notes().'
  print '4. You can now enter the shop by typing shop, trade or sell.'
  print '5. Edit_chapters now imports vars correctly.'
  print '6. You can now load settings.dev in the home menu in dev mode.'
  print '7. Developers can now clear cache if for somereason python is not responding with the given code as expected.'
  print '8. Added a new setting to allow loading of old save file.'
  print '9. Added a warning at the end of the save file.'
  print '10. Edited the enemy name list.'
  print '11. Added a sleeping function. Time goes by and shop prices change.'
  print '12. Added a stats menu. Currently only usable in dev mode.'
  print '13. Added levels, xp, and strength for player after completing a battle.'
  print '14. Users can now exit dev mode in the home menu.'
if code == "0.2.8":
  print 'Current Version 0.2.8'
  print '1. Fixed SyntaxWarning at game startup.'
  print '2. Changed how the damage menu looks to the end user.'
  print '3. Changed the print repeat Value from 25 to 55.'
  print '4. Fixed many bugs in different menus in different secenerios.'
